language: julia
os:
  - linux
  - osx
julia:
  - nightly
matrix:
  allow_failures:
   - julia: nightly
notifications:
  email: true
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Jags"); Pkg.test("Jags")'

