language: julia

os:
  - linux
  - osx
  
julia:
  - 1.0
  - 1.1
  - nightly
  
matrix:
  allow_failures:
   - julia: nightly
   - os: osx
   
notifications:
  email: true
  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.develop("Jags"); Pkg.test("Jags"; coverage=true)'

