language: julia

os:
  - linux
  - osx
  
julia:
  - 0.6
  - 0.7
  - nightly
  
matrix:
  allow_failures:
   - julia: nightly
   -julia: 0.7
   
notifications:
  email: true
  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg.clone(pwd()); Pkg.test("Jags")'

